from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(582, 394)

        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(390, 290, 160, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton.setEnabled(False)
        self.pushButton.clicked.connect(self.Continue)

        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_2.clicked.connect(self.Exit)

        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(70, 70, 121, 238))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setMaximumSize(QtCore.QSize(158, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)

        self.Chap00 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.Chap00.setFont(font)
        self.Chap00.setObjectName("Chap00")
        self.verticalLayout_3.addWidget(self.Chap00)
        self.Chap00.stateChanged.connect(lambda: self.btnstate(self.Chap00))
        self.Chap00.stateChanged.connect(lambda: self.chapState(self.Chap00))

        self.Chap01 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.Chap01.setFont(font)
        self.Chap01.setObjectName("Chap01")
        self.verticalLayout_3.addWidget(self.Chap01)
        self.Chap01.stateChanged.connect(lambda: self.btnstate(self.Chap01))
        self.Chap01.stateChanged.connect(lambda: self.chapState(self.Chap01))

        self.Chap02 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.Chap02.setFont(font)
        self.Chap02.setObjectName("Chap02")
        self.verticalLayout_3.addWidget(self.Chap02)
        self.Chap02.stateChanged.connect(lambda: self.btnstate(self.Chap02))
        self.Chap02.stateChanged.connect(lambda: self.chapState(self.Chap02))

        self.Chap03 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.Chap03.setFont(font)
        self.Chap03.setObjectName("Chap03")
        self.verticalLayout_3.addWidget(self.Chap03)
        self.Chap03.stateChanged.connect(lambda: self.btnstate(self.Chap03))
        self.Chap03.stateChanged.connect(lambda: self.chapState(self.Chap03))

        self.Chap04 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.Chap04.setFont(font)
        self.Chap04.setObjectName("Chap04")
        self.verticalLayout_3.addWidget(self.Chap04)
        self.Chap04.stateChanged.connect(lambda: self.btnstate(self.Chap04))
        self.Chap04.stateChanged.connect(lambda: self.chapState(self.Chap04))

        self.Chap05 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.Chap05.setFont(font)
        self.Chap05.setObjectName("Chap05")
        self.verticalLayout_3.addWidget(self.Chap05)
        self.Chap05.stateChanged.connect(lambda: self.btnstate(self.Chap05))
        self.Chap05.stateChanged.connect(lambda: self.chapState(self.Chap05))

        self.Chap06 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.Chap06.setFont(font)
        self.Chap06.setObjectName("Chap06")
        self.verticalLayout_3.addWidget(self.Chap06)
        self.Chap06.stateChanged.connect(lambda: self.btnstate(self.Chap06))
        self.Chap06.stateChanged.connect(lambda: self.chapState(self.Chap06))

        self.Chap07 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.Chap07.setFont(font)
        self.Chap07.setObjectName("Chap07")
        self.verticalLayout_3.addWidget(self.Chap07)
        self.Chap07.stateChanged.connect(lambda: self.btnstate(self.Chap07))
        self.Chap07.stateChanged.connect(lambda: self.chapState(self.Chap07))

        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(380, 70, 141, 131))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_3.setMaximumSize(QtCore.QSize(158, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)

        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, 0, -1, 0)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")

        self.comboBox_Judge = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.comboBox_Judge.setObjectName("comboBox_Judge")
        self.comboBox_Judge.currentIndexChanged.connect(self.selectionChange)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_Judge)

        self.comboBox_Sgl = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.comboBox_Sgl.setObjectName("comboBox_Sgl")
        self.comboBox_Sgl.currentIndexChanged.connect(self.selectionChange)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_Sgl)

        self.comboBox_Mul = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.comboBox_Mul.setObjectName("comboBox_Mul")
        self.comboBox_Mul.currentIndexChanged.connect(self.selectionChange)
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_Mul)

        self.verticalLayout_4.addLayout(self.formLayout)

        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(260, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        for n in range(1, 101):
            self.comboBox_Judge.addItem("{}".format(n))
            self.comboBox_Sgl.addItem("{}".format(n))
            self.comboBox_Mul.addItem("{}".format(n))

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "进入顺序练习"))
        self.pushButton.setText(_translate("Dialog", "确认"))
        self.pushButton_2.setText(_translate("Dialog", "取消"))
        self.label_2.setText(_translate("Dialog", "章节选择"))
        self.Chap00.setText(_translate("Dialog", "绪论"))
        self.Chap01.setText(_translate("Dialog", "第一章"))
        self.Chap02.setText(_translate("Dialog", "第二章"))
        self.Chap03.setText(_translate("Dialog", "第三章"))
        self.Chap04.setText(_translate("Dialog", "第四章"))
        self.Chap05.setText(_translate("Dialog", "第五章"))
        self.Chap06.setText(_translate("Dialog", "第六章"))
        self.Chap07.setText(_translate("Dialog", "第七章"))
        self.label_3.setText(_translate("Dialog", "题型选择"))
        self.label_5.setText(_translate("Dialog", "判断题"))
        self.label_6.setText(_translate("Dialog", "单选题"))
        self.label_7.setText(_translate("Dialog", "多选题"))
        self.label.setText(_translate("Dialog", "专项选择"))