# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_registerWindow(object):
    def setupUi(self, registerWindow):
        registerWindow.setObjectName("registerWindow")
        registerWindow.resize(649, 428)
        self.centralwidget = QtWidgets.QWidget(registerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_register_name = QtWidgets.QLabel(self.centralwidget)
        self.label_register_name.setGeometry(QtCore.QRect(130, 60, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_register_name.setFont(font)
        self.label_register_name.setObjectName("label_register_name")
        self.label_register_pwd = QtWidgets.QLabel(self.centralwidget)
        self.label_register_pwd.setGeometry(QtCore.QRect(130, 140, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_register_pwd.setFont(font)
        self.label_register_pwd.setObjectName("label_register_pwd")
        self.label_register_pwd2 = QtWidgets.QLabel(self.centralwidget)
        self.label_register_pwd2.setGeometry(QtCore.QRect(130, 220, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_register_pwd2.setFont(font)
        self.label_register_pwd2.setObjectName("label_register_pwd2")
        self.lineEdit_register_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_register_name.setGeometry(QtCore.QRect(270, 60, 261, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.lineEdit_register_name.setFont(font)
        self.lineEdit_register_name.setObjectName("lineEdit_register_name")
        self.lineEdit_register_pwd1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_register_pwd1.setGeometry(QtCore.QRect(270, 140, 261, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.lineEdit_register_pwd1.setFont(font)
        self.lineEdit_register_pwd1.setObjectName("lineEdit_register_pwd1")
        self.lineEdit_register_pwd2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_register_pwd2.setGeometry(QtCore.QRect(270, 220, 261, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.lineEdit_register_pwd2.setFont(font)
        self.lineEdit_register_pwd2.setObjectName("lineEdit_register_pwd2")
        self.confirmButton = QtWidgets.QPushButton(self.centralwidget)
        self.confirmButton.setGeometry(QtCore.QRect(130, 280, 131, 51))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(14)
        self.confirmButton.setFont(font)
        self.confirmButton.setObjectName("confirmButton")
        self.returnButton = QtWidgets.QPushButton(self.centralwidget)
        self.returnButton.setGeometry(QtCore.QRect(400, 280, 131, 51))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(14)
        self.returnButton.setFont(font)
        self.returnButton.setObjectName("returnButton")
        self.tip_label2 = QtWidgets.QLabel(self.centralwidget)
        self.tip_label2.setGeometry(QtCore.QRect(540, 64, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.tip_label2.setFont(font)
        self.tip_label2.setStyleSheet("color: rgb(255, 52, 12);")
        self.tip_label2.setText("")
        self.tip_label2.setWordWrap(True)
        self.tip_label2.setObjectName("tip_label2")
        self.tip_label3 = QtWidgets.QLabel(self.centralwidget)
        self.tip_label3.setGeometry(QtCore.QRect(540, 210, 91, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.tip_label3.setFont(font)
        self.tip_label3.setStyleSheet("color: rgb(255, 52, 12);")
        self.tip_label3.setLineWidth(0)
        self.tip_label3.setText("")
        self.tip_label3.setWordWrap(True)
        self.tip_label3.setObjectName("tip_label3")
        registerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(registerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 649, 26))
        self.menubar.setObjectName("menubar")
        registerWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(registerWindow)
        self.statusbar.setObjectName("statusbar")
        registerWindow.setStatusBar(self.statusbar)

        self.retranslateUi(registerWindow)
        QtCore.QMetaObject.connectSlotsByName(registerWindow)

    def retranslateUi(self, registerWindow):
        _translate = QtCore.QCoreApplication.translate
        registerWindow.setWindowTitle(_translate("registerWindow", "注册"))
        self.label_register_name.setText(_translate("registerWindow", "用户名："))
        self.label_register_pwd.setText(_translate("registerWindow", "密码："))
        self.label_register_pwd2.setText(_translate("registerWindow", "确认密码："))
        self.confirmButton.setText(_translate("registerWindow", "确定"))
        self.returnButton.setText(_translate("registerWindow", "返回"))
