# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_register_window(object):
    def setupUi(self, register_window):
        register_window.setObjectName("register_window")
        register_window.resize(649, 428)
        self.centralwidget = QtWidgets.QWidget(register_window)
        self.centralwidget.setObjectName("centralwidget")
        self.labelRegisterName = QtWidgets.QLabel(self.centralwidget)
        self.labelRegisterName.setGeometry(QtCore.QRect(130, 60, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.labelRegisterName.setFont(font)
        self.labelRegisterName.setObjectName("labelRegisterName")
        self.labelRegisterPwd1 = QtWidgets.QLabel(self.centralwidget)
        self.labelRegisterPwd1.setGeometry(QtCore.QRect(130, 140, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.labelRegisterPwd1.setFont(font)
        self.labelRegisterPwd1.setObjectName("labelRegisterPwd1")
        self.labelRegisterPwd2 = QtWidgets.QLabel(self.centralwidget)
        self.labelRegisterPwd2.setGeometry(QtCore.QRect(130, 220, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.labelRegisterPwd2.setFont(font)
        self.labelRegisterPwd2.setObjectName("labelRegisterPwd2")
        self.lineEditRegisterName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditRegisterName.setGeometry(QtCore.QRect(270, 60, 261, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.lineEditRegisterName.setFont(font)
        self.lineEditRegisterName.setObjectName("lineEditRegisterName")
        self.lineEditRegisterPwd1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditRegisterPwd1.setGeometry(QtCore.QRect(270, 140, 261, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.lineEditRegisterPwd1.setFont(font)
        self.lineEditRegisterPwd1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditRegisterPwd1.setObjectName("lineEditRegisterPwd1")
        self.lineEditRegisterPwd2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditRegisterPwd2.setGeometry(QtCore.QRect(270, 220, 261, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.lineEditRegisterPwd2.setFont(font)
        self.lineEditRegisterPwd2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditRegisterPwd2.setObjectName("lineEditRegisterPwd2")
        self.confirmButton = QtWidgets.QPushButton(self.centralwidget)
        self.confirmButton.setGeometry(QtCore.QRect(130, 280, 131, 51))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(14)
        self.confirmButton.setFont(font)
        self.confirmButton.setObjectName("confirmButton")
        self.returnButton = QtWidgets.QPushButton(self.centralwidget)
        self.returnButton.setGeometry(QtCore.QRect(400, 280, 131, 51))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(14)
        self.returnButton.setFont(font)
        self.returnButton.setObjectName("returnButton")
        self.tipLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.tipLabel2.setGeometry(QtCore.QRect(540, 64, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.tipLabel2.setFont(font)
        self.tipLabel2.setStyleSheet("color: rgb(255, 52, 12);")
        self.tipLabel2.setText("")
        self.tipLabel2.setWordWrap(True)
        self.tipLabel2.setObjectName("tipLabel2")
        self.tipLabel3 = QtWidgets.QLabel(self.centralwidget)
        self.tipLabel3.setGeometry(QtCore.QRect(540, 210, 91, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.tipLabel3.setFont(font)
        self.tipLabel3.setStyleSheet("color: rgb(255, 52, 12);")
        self.tipLabel3.setLineWidth(0)
        self.tipLabel3.setText("")
        self.tipLabel3.setWordWrap(True)
        self.tipLabel3.setObjectName("tipLabel3")
        self.tipLabel4 = QtWidgets.QLabel(self.centralwidget)
        self.tipLabel4.setGeometry(QtCore.QRect(240, 190, 391, 20))
        self.tipLabel4.setObjectName("tipLabel4")
        register_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(register_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 649, 26))
        self.menubar.setObjectName("menubar")
        register_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(register_window)
        self.statusbar.setObjectName("statusbar")
        register_window.setStatusBar(self.statusbar)

        self.retranslateUi(register_window)
        QtCore.QMetaObject.connectSlotsByName(register_window)

    def retranslateUi(self, register_window):
        _translate = QtCore.QCoreApplication.translate
        register_window.setWindowTitle(_translate("register_window", "注册"))
        self.labelRegisterName.setText(_translate("register_window", "用户名："))
        self.labelRegisterPwd1.setText(_translate("register_window", "密码："))
        self.labelRegisterPwd2.setText(_translate("register_window", "确认密码："))
        self.confirmButton.setText(_translate("register_window", "确定"))
        self.returnButton.setText(_translate("register_window", "返回"))
        self.tipLabel4.setText(_translate("register_window", "密码只能含有数字和字母，并且只能以字母开头"))
